### PR TITLE
replace cereal with binary to be able to parse streams

### PR DESCRIPTION
**Pull request by osa1**
See also #4 .

### CODE REVIEW

**Comment by rodrigosetti** [comment]
Cool. thanks for the PR.

Do you mind also doing the following?

 * Update [README.md](/rodrigosetti/messagepack/blob/master/README.md)
 * Update [.cabal](/rodrigosetti/messagepack/blob/master/messagepack.cabal) synopsis and description
 * Bump [.cabal](/rodrigosetti/messagepack/blob/master/messagepack.cabal) version to 0.4.0 (as this breaks compatibility)
 * Add an entry in [CHANGELOG](/rodrigosetti/messagepack/blob/master/CHANGELOG)

**Comment by osa1** [comment]
Sure, I'll do that in a few hours.

**Comment by osa1** [comment]
Hm, it turns out `cereal` also has the same exact API: http://hackage.haskell.org/package/cereal-0.4.1.1/docs/Data-Serialize-Get.html#v:runGetPartial maybe I should read the docs more carefully. Closing this PR.

**Comment by rodrigosetti** [comment]
oh, nice. I didn't know that too.

**Pull request closed without merging**
